### ISSUE TITLE
Provide versioned binary packages

### ISSUE THREAD

**Issue by zhassan-aws** [diffblue/homebrew-cbmc#3]
Thanks for creating this homebrew tap! This is really helpful for installing specific versions of CBMC!

Is it possible to add the bottle information (pre-built binary packages) for the formulae in this homebrew tap, so that installing them wouldn't build CBMC from source? Currently, installing CBMC from this tap using `brew install diffblue/cbmc/cbmc@5.56.0` takes more than 20 minutes:

https://github.com/model-checking/kani/runs/6374211806?check_suite_focus=true#step:3:198

See https://docs.brew.sh/Bottles for more information.

**Comment by NlightNFotis** [comment]
Hello,

I'm a bit apprehensive towards adding references to bottles maintained by upstream homebrew, because I'm not sure what their artefact retention policy is.

For instance, today we're on schedule to release 5.57.0? What happens to the 5.56.0 binaries they store? I think they just delete/overwrite them (but I need to research more on that).

If that is the case, then the binary references we add to the formulas in this tap are going to become stale very very fast.

Let me do some further research on this, and if binaries are very important for you, we could further discuss it within the context of our bi-weekly meeting to find a way to store binaries somewhere so that they are retained for the various CBMC releases.

**Comment by zhassan-aws** [comment]
I have the same concern, and I'm not clear on how upstream homebrew handles binaries. I think it might be possible to store the binaries somewhere else, perhaps in this repo, and add it as the root URL of the formula:

https://docs.brew.sh/Bottles#root-url-root_url

Thanks for looking into this @NlightNFotis!

**Comment by tautschnig** [comment]
@NlightNFotis If it's of any help: https://github.com/aws/homebrew-tap/blob/master/Formula/cbmc-viewer.rb is how this is being handled for some of our other software. Note the pointers to the release page in there. The workflows building the releases can be found at https://github.com/model-checking/cbmc-viewer/tree/master/.github/workflows.

**Comment by NlightNFotis** [comment]
Hi Michael @tautschnig, very much appreciate the pointers.

I managed to get the tap binaries to be working for me, and I believe they should be working for the formula versions `5.60.0` and `5.59.0` in this repository.

Could you please have a look if it works for you as well? Assuming it does and there are no hurdles, I'm happy to add the binaries for all the other versions of CMBC in the tap.

**Comment by zhassan-aws** [comment]
I try using the binary packages, but ran into an error in Kani's CI: https://github.com/model-checking/kani/runs/7290731226?check_suite_focus=true

This seems similar to the error in https://github.com/Homebrew/brew/issues/2373.

**Comment by NlightNFotis** [comment]
Thanks for having a look @zhassan-aws - I'll investigate this on an ASAP basis.

**Comment by NlightNFotis** [comment]
Hi @zhassan-aws, I have implemented a fix for the binaries of version `5.61.0`.

Could you please confirm it works from your end as well?

If it does, I'm going to go ahead and implement the same fix for the last couple of versions as well (`5.60.0` and `5.59.0`).

Thanks for your patience with this.

**Comment by zhassan-aws** [comment]
That did the trick! Thanks @NlightNFotis!

**Comment by zhassan-aws** [comment]
FYI, as of https://github.com/model-checking/kani/commit/beedd6ae6310167b44d3f79db41835b217131117, the cbmc tap and the pre-packaged binaries are used in Kani's CI!

Thanks a lot for implementing this, @NlightNFotis!
